version: '3.8'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./public:/usr/share/nginx/html:ro
        environment:
            - NGINX_SERVER_NAME=localhost
        working_dir: /app
        ports:
            - '80:80'
