version: '3.8'
name: beholder_map
services:
    nginx:
        image: docker.io/library/nginx:latest
        volumes:
            - ./public:/usr/share/nginx/html:ro
        environment:
            - NGINX_SERVER_NAME=localhost
        ports:
            - '8080:80'
